// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 05 Aug 2020 10:29:11 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package bcm2835go

/*
#include "bcm2835.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// Bcm2835_init function as declared in bcm-go/bcm2835.h:1291
func Bcm2835_init() int32 {
	__ret := C.bcm2835_init()
	__v := (int32)(__ret)
	return __v
}

// Bcm2835_close function as declared in bcm-go/bcm2835.h:1296
func Bcm2835_close() int32 {
	__ret := C.bcm2835_close()
	__v := (int32)(__ret)
	return __v
}

// Bcm2835_set_debug function as declared in bcm-go/bcm2835.h:1305
func Bcm2835_set_debug(Debug byte) {
	cDebug, _ := (C.uint8_t)(Debug), cgoAllocsUnknown
	C.bcm2835_set_debug(cDebug)
}

// Bcm2835_version function as declared in bcm-go/bcm2835.h:1310
func Bcm2835_version() uint32 {
	__ret := C.bcm2835_version()
	__v := (uint32)(__ret)
	return __v
}

// Bcm2835_regbase function as declared in bcm-go/bcm2835.h:1327
func Bcm2835_regbase(Regbase byte) *uint32 {
	cRegbase, _ := (C.uint8_t)(Regbase), cgoAllocsUnknown
	__ret := C.bcm2835_regbase(cRegbase)
	__v := *(**uint32)(unsafe.Pointer(&__ret))
	return __v
}

// Bcm2835_peri_read function as declared in bcm-go/bcm2835.h:1337
func Bcm2835_peri_read(Paddr []uint32) uint32 {
	cPaddr, _ := (*C.uint32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Paddr)).Data)), cgoAllocsUnknown
	__ret := C.bcm2835_peri_read(cPaddr)
	__v := (uint32)(__ret)
	return __v
}

// Bcm2835_peri_read_nb function as declared in bcm-go/bcm2835.h:1349
func Bcm2835_peri_read_nb(Paddr []uint32) uint32 {
	cPaddr, _ := (*C.uint32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Paddr)).Data)), cgoAllocsUnknown
	__ret := C.bcm2835_peri_read_nb(cPaddr)
	__v := (uint32)(__ret)
	return __v
}

// Bcm2835_peri_write function as declared in bcm-go/bcm2835.h:1363
func Bcm2835_peri_write(Paddr []uint32, Value uint32) {
	cPaddr, _ := (*C.uint32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Paddr)).Data)), cgoAllocsUnknown
	cValue, _ := (C.uint32_t)(Value), cgoAllocsUnknown
	C.bcm2835_peri_write(cPaddr, cValue)
}

// Bcm2835_peri_write_nb function as declared in bcm-go/bcm2835.h:1377
func Bcm2835_peri_write_nb(Paddr []uint32, Value uint32) {
	cPaddr, _ := (*C.uint32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Paddr)).Data)), cgoAllocsUnknown
	cValue, _ := (C.uint32_t)(Value), cgoAllocsUnknown
	C.bcm2835_peri_write_nb(cPaddr, cValue)
}

// Bcm2835_peri_set_bits function as declared in bcm-go/bcm2835.h:1391
func Bcm2835_peri_set_bits(Paddr []uint32, Value uint32, Mask uint32) {
	cPaddr, _ := (*C.uint32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Paddr)).Data)), cgoAllocsUnknown
	cValue, _ := (C.uint32_t)(Value), cgoAllocsUnknown
	cMask, _ := (C.uint32_t)(Mask), cgoAllocsUnknown
	C.bcm2835_peri_set_bits(cPaddr, cValue, cMask)
}

// Bcm2835_gpio_fsel function as declared in bcm-go/bcm2835.h:1405
func Bcm2835_gpio_fsel(Pin byte, Mode byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	cMode, _ := (C.uint8_t)(Mode), cgoAllocsUnknown
	C.bcm2835_gpio_fsel(cPin, cMode)
}

// Bcm2835_gpio_set function as declared in bcm-go/bcm2835.h:1412
func Bcm2835_gpio_set(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_set(cPin)
}

// Bcm2835_gpio_clr function as declared in bcm-go/bcm2835.h:1419
func Bcm2835_gpio_clr(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_clr(cPin)
}

// Bcm2835_gpio_set_multi function as declared in bcm-go/bcm2835.h:1426
func Bcm2835_gpio_set_multi(Mask uint32) {
	cMask, _ := (C.uint32_t)(Mask), cgoAllocsUnknown
	C.bcm2835_gpio_set_multi(cMask)
}

// Bcm2835_gpio_clr_multi function as declared in bcm-go/bcm2835.h:1433
func Bcm2835_gpio_clr_multi(Mask uint32) {
	cMask, _ := (C.uint32_t)(Mask), cgoAllocsUnknown
	C.bcm2835_gpio_clr_multi(cMask)
}

// Bcm2835_gpio_lev function as declared in bcm-go/bcm2835.h:1441
func Bcm2835_gpio_lev(Pin byte) byte {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	__ret := C.bcm2835_gpio_lev(cPin)
	__v := (byte)(__ret)
	return __v
}

// Bcm2835_gpio_eds function as declared in bcm-go/bcm2835.h:1451
func Bcm2835_gpio_eds(Pin byte) byte {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	__ret := C.bcm2835_gpio_eds(cPin)
	__v := (byte)(__ret)
	return __v
}

// Bcm2835_gpio_eds_multi function as declared in bcm-go/bcm2835.h:1458
func Bcm2835_gpio_eds_multi(Mask uint32) uint32 {
	cMask, _ := (C.uint32_t)(Mask), cgoAllocsUnknown
	__ret := C.bcm2835_gpio_eds_multi(cMask)
	__v := (uint32)(__ret)
	return __v
}

// Bcm2835_gpio_set_eds function as declared in bcm-go/bcm2835.h:1465
func Bcm2835_gpio_set_eds(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_set_eds(cPin)
}

// Bcm2835_gpio_set_eds_multi function as declared in bcm-go/bcm2835.h:1471
func Bcm2835_gpio_set_eds_multi(Mask uint32) {
	cMask, _ := (C.uint32_t)(Mask), cgoAllocsUnknown
	C.bcm2835_gpio_set_eds_multi(cMask)
}

// Bcm2835_gpio_ren function as declared in bcm-go/bcm2835.h:1481
func Bcm2835_gpio_ren(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_ren(cPin)
}

// Bcm2835_gpio_clr_ren function as declared in bcm-go/bcm2835.h:1486
func Bcm2835_gpio_clr_ren(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_clr_ren(cPin)
}

// Bcm2835_gpio_fen function as declared in bcm-go/bcm2835.h:1496
func Bcm2835_gpio_fen(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_fen(cPin)
}

// Bcm2835_gpio_clr_fen function as declared in bcm-go/bcm2835.h:1501
func Bcm2835_gpio_clr_fen(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_clr_fen(cPin)
}

// Bcm2835_gpio_hen function as declared in bcm-go/bcm2835.h:1507
func Bcm2835_gpio_hen(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_hen(cPin)
}

// Bcm2835_gpio_clr_hen function as declared in bcm-go/bcm2835.h:1512
func Bcm2835_gpio_clr_hen(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_clr_hen(cPin)
}

// Bcm2835_gpio_len function as declared in bcm-go/bcm2835.h:1518
func Bcm2835_gpio_len(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_len(cPin)
}

// Bcm2835_gpio_clr_len function as declared in bcm-go/bcm2835.h:1523
func Bcm2835_gpio_clr_len(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_clr_len(cPin)
}

// Bcm2835_gpio_aren function as declared in bcm-go/bcm2835.h:1531
func Bcm2835_gpio_aren(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_aren(cPin)
}

// Bcm2835_gpio_clr_aren function as declared in bcm-go/bcm2835.h:1536
func Bcm2835_gpio_clr_aren(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_clr_aren(cPin)
}

// Bcm2835_gpio_afen function as declared in bcm-go/bcm2835.h:1544
func Bcm2835_gpio_afen(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_afen(cPin)
}

// Bcm2835_gpio_clr_afen function as declared in bcm-go/bcm2835.h:1549
func Bcm2835_gpio_clr_afen(Pin byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	C.bcm2835_gpio_clr_afen(cPin)
}

// Bcm2835_gpio_pud function as declared in bcm-go/bcm2835.h:1559
func Bcm2835_gpio_pud(Pud byte) {
	cPud, _ := (C.uint8_t)(Pud), cgoAllocsUnknown
	C.bcm2835_gpio_pud(cPud)
}

// Bcm2835_gpio_pudclk function as declared in bcm-go/bcm2835.h:1571
func Bcm2835_gpio_pudclk(Pin byte, On byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	cOn, _ := (C.uint8_t)(On), cgoAllocsUnknown
	C.bcm2835_gpio_pudclk(cPin, cOn)
}

// Bcm2835_gpio_pad function as declared in bcm-go/bcm2835.h:1578
func Bcm2835_gpio_pad(Group byte) uint32 {
	cGroup, _ := (C.uint8_t)(Group), cgoAllocsUnknown
	__ret := C.bcm2835_gpio_pad(cGroup)
	__v := (uint32)(__ret)
	return __v
}

// Bcm2835_gpio_set_pad function as declared in bcm-go/bcm2835.h:1587
func Bcm2835_gpio_set_pad(Group byte, Control uint32) {
	cGroup, _ := (C.uint8_t)(Group), cgoAllocsUnknown
	cControl, _ := (C.uint32_t)(Control), cgoAllocsUnknown
	C.bcm2835_gpio_set_pad(cGroup, cControl)
}

// Bcm2835_delay function as declared in bcm-go/bcm2835.h:1599
func Bcm2835_delay(Millis uint32) {
	cMillis, _ := (C.uint)(Millis), cgoAllocsUnknown
	C.bcm2835_delay(cMillis)
}

// Bcm2835_delayMicroseconds function as declared in bcm-go/bcm2835.h:1614
func Bcm2835_delayMicroseconds(Micros uint64) {
	cMicros, _ := (C.uint64_t)(Micros), cgoAllocsUnknown
	C.bcm2835_delayMicroseconds(cMicros)
}

// Bcm2835_gpio_write function as declared in bcm-go/bcm2835.h:1620
func Bcm2835_gpio_write(Pin byte, On byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	cOn, _ := (C.uint8_t)(On), cgoAllocsUnknown
	C.bcm2835_gpio_write(cPin, cOn)
}

// Bcm2835_gpio_write_multi function as declared in bcm-go/bcm2835.h:1626
func Bcm2835_gpio_write_multi(Mask uint32, On byte) {
	cMask, _ := (C.uint32_t)(Mask), cgoAllocsUnknown
	cOn, _ := (C.uint8_t)(On), cgoAllocsUnknown
	C.bcm2835_gpio_write_multi(cMask, cOn)
}

// Bcm2835_gpio_write_mask function as declared in bcm-go/bcm2835.h:1632
func Bcm2835_gpio_write_mask(Value uint32, Mask uint32) {
	cValue, _ := (C.uint32_t)(Value), cgoAllocsUnknown
	cMask, _ := (C.uint32_t)(Mask), cgoAllocsUnknown
	C.bcm2835_gpio_write_mask(cValue, cMask)
}

// Bcm2835_gpio_set_pud function as declared in bcm-go/bcm2835.h:1639
func Bcm2835_gpio_set_pud(Pin byte, Pud byte) {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	cPud, _ := (C.uint8_t)(Pud), cgoAllocsUnknown
	C.bcm2835_gpio_set_pud(cPin, cPud)
}

// Bcm2835_gpio_get_pud function as declared in bcm-go/bcm2835.h:1647
func Bcm2835_gpio_get_pud(Pin byte) byte {
	cPin, _ := (C.uint8_t)(Pin), cgoAllocsUnknown
	__ret := C.bcm2835_gpio_get_pud(cPin)
	__v := (byte)(__ret)
	return __v
}

// Bcm2835_spi_begin function as declared in bcm-go/bcm2835.h:1665
func Bcm2835_spi_begin() int32 {
	__ret := C.bcm2835_spi_begin()
	__v := (int32)(__ret)
	return __v
}

// Bcm2835_spi_end function as declared in bcm-go/bcm2835.h:1671
func Bcm2835_spi_end() {
	C.bcm2835_spi_end()
}

// Bcm2835_spi_setBitOrder function as declared in bcm-go/bcm2835.h:1680
func Bcm2835_spi_setBitOrder(Order byte) {
	cOrder, _ := (C.uint8_t)(Order), cgoAllocsUnknown
	C.bcm2835_spi_setBitOrder(cOrder)
}

// Bcm2835_spi_setClockDivider function as declared in bcm-go/bcm2835.h:1687
func Bcm2835_spi_setClockDivider(Divider uint16) {
	cDivider, _ := (C.uint16_t)(Divider), cgoAllocsUnknown
	C.bcm2835_spi_setClockDivider(cDivider)
}

// Bcm2835_spi_set_speed_hz function as declared in bcm-go/bcm2835.h:1693
func Bcm2835_spi_set_speed_hz(Speed_hz uint32) {
	cSpeed_hz, _ := (C.uint32_t)(Speed_hz), cgoAllocsUnknown
	C.bcm2835_spi_set_speed_hz(cSpeed_hz)
}

// Bcm2835_spi_setDataMode function as declared in bcm-go/bcm2835.h:1700
func Bcm2835_spi_setDataMode(Mode byte) {
	cMode, _ := (C.uint8_t)(Mode), cgoAllocsUnknown
	C.bcm2835_spi_setDataMode(cMode)
}

// Bcm2835_spi_chipSelect function as declared in bcm-go/bcm2835.h:1708
func Bcm2835_spi_chipSelect(Cs byte) {
	cCs, _ := (C.uint8_t)(Cs), cgoAllocsUnknown
	C.bcm2835_spi_chipSelect(cCs)
}

// Bcm2835_spi_setChipSelectPolarity function as declared in bcm-go/bcm2835.h:1718
func Bcm2835_spi_setChipSelectPolarity(Cs byte, Active byte) {
	cCs, _ := (C.uint8_t)(Cs), cgoAllocsUnknown
	cActive, _ := (C.uint8_t)(Active), cgoAllocsUnknown
	C.bcm2835_spi_setChipSelectPolarity(cCs, cActive)
}

// Bcm2835_spi_transfer function as declared in bcm-go/bcm2835.h:1730
func Bcm2835_spi_transfer(Value byte) byte {
	cValue, _ := (C.uint8_t)(Value), cgoAllocsUnknown
	__ret := C.bcm2835_spi_transfer(cValue)
	__v := (byte)(__ret)
	return __v
}

// Bcm2835_spi_transfernb function as declared in bcm-go/bcm2835.h:1743
func Bcm2835_spi_transfernb(Tbuf []byte, Rbuf []byte, Len uint32) {
	cTbuf, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Tbuf)).Data)), cgoAllocsUnknown
	cRbuf, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Rbuf)).Data)), cgoAllocsUnknown
	cLen, _ := (C.uint32_t)(Len), cgoAllocsUnknown
	C.bcm2835_spi_transfernb(cTbuf, cRbuf, cLen)
}

// Bcm2835_spi_transfern function as declared in bcm-go/bcm2835.h:1752
func Bcm2835_spi_transfern(Buf []byte, Len uint32) {
	cBuf, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Buf)).Data)), cgoAllocsUnknown
	cLen, _ := (C.uint32_t)(Len), cgoAllocsUnknown
	C.bcm2835_spi_transfern(cBuf, cLen)
}

// Bcm2835_spi_writenb function as declared in bcm-go/bcm2835.h:1760
func Bcm2835_spi_writenb(Buf string, Len uint32) {
	Buf = safeString(Buf)
	cBuf, _ := unpackPCharString(Buf)
	cLen, _ := (C.uint32_t)(Len), cgoAllocsUnknown
	C.bcm2835_spi_writenb(cBuf, cLen)
	runtime.KeepAlive(Buf)
}

// Bcm2835_spi_write function as declared in bcm-go/bcm2835.h:1770
func Bcm2835_spi_write(Data uint16) {
	cData, _ := (C.uint16_t)(Data), cgoAllocsUnknown
	C.bcm2835_spi_write(cData)
}

// Bcm2835_aux_spi_begin function as declared in bcm-go/bcm2835.h:1777
func Bcm2835_aux_spi_begin() int32 {
	__ret := C.bcm2835_aux_spi_begin()
	__v := (int32)(__ret)
	return __v
}

// Bcm2835_aux_spi_end function as declared in bcm-go/bcm2835.h:1783
func Bcm2835_aux_spi_end() {
	C.bcm2835_aux_spi_end()
}

// Bcm2835_aux_spi_setClockDivider function as declared in bcm-go/bcm2835.h:1788
func Bcm2835_aux_spi_setClockDivider(Divider uint16) {
	cDivider, _ := (C.uint16_t)(Divider), cgoAllocsUnknown
	C.bcm2835_aux_spi_setClockDivider(cDivider)
}

// Bcm2835_aux_spi_CalcClockDivider function as declared in bcm-go/bcm2835.h:1795
func Bcm2835_aux_spi_CalcClockDivider(Speed_hz uint32) uint16 {
	cSpeed_hz, _ := (C.uint32_t)(Speed_hz), cgoAllocsUnknown
	__ret := C.bcm2835_aux_spi_CalcClockDivider(cSpeed_hz)
	__v := (uint16)(__ret)
	return __v
}

// Bcm2835_aux_spi_write function as declared in bcm-go/bcm2835.h:1803
func Bcm2835_aux_spi_write(Data uint16) {
	cData, _ := (C.uint16_t)(Data), cgoAllocsUnknown
	C.bcm2835_aux_spi_write(cData)
}

// Bcm2835_aux_spi_writenb function as declared in bcm-go/bcm2835.h:1810
func Bcm2835_aux_spi_writenb(Buf string, Len uint32) {
	Buf = safeString(Buf)
	cBuf, _ := unpackPCharString(Buf)
	cLen, _ := (C.uint32_t)(Len), cgoAllocsUnknown
	C.bcm2835_aux_spi_writenb(cBuf, cLen)
	runtime.KeepAlive(Buf)
}

// Bcm2835_aux_spi_transfern function as declared in bcm-go/bcm2835.h:1819
func Bcm2835_aux_spi_transfern(Buf []byte, Len uint32) {
	cBuf, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Buf)).Data)), cgoAllocsUnknown
	cLen, _ := (C.uint32_t)(Len), cgoAllocsUnknown
	C.bcm2835_aux_spi_transfern(cBuf, cLen)
}

// Bcm2835_aux_spi_transfernb function as declared in bcm-go/bcm2835.h:1829
func Bcm2835_aux_spi_transfernb(Tbuf string, Rbuf []byte, Len uint32) {
	Tbuf = safeString(Tbuf)
	cTbuf, _ := unpackPCharString(Tbuf)
	cRbuf, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Rbuf)).Data)), cgoAllocsUnknown
	cLen, _ := (C.uint32_t)(Len), cgoAllocsUnknown
	C.bcm2835_aux_spi_transfernb(cTbuf, cRbuf, cLen)
	runtime.KeepAlive(Tbuf)
}

// Bcm2835_aux_spi_transfer function as declared in bcm-go/bcm2835.h:1838
func Bcm2835_aux_spi_transfer(Value byte) byte {
	cValue, _ := (C.uint8_t)(Value), cgoAllocsUnknown
	__ret := C.bcm2835_aux_spi_transfer(cValue)
	__v := (byte)(__ret)
	return __v
}

// Bcm2835_i2c_begin function as declared in bcm-go/bcm2835.h:1856
func Bcm2835_i2c_begin() int32 {
	__ret := C.bcm2835_i2c_begin()
	__v := (int32)(__ret)
	return __v
}

// Bcm2835_i2c_end function as declared in bcm-go/bcm2835.h:1862
func Bcm2835_i2c_end() {
	C.bcm2835_i2c_end()
}

// Bcm2835_i2c_setSlaveAddress function as declared in bcm-go/bcm2835.h:1867
func Bcm2835_i2c_setSlaveAddress(Addr byte) {
	cAddr, _ := (C.uint8_t)(Addr), cgoAllocsUnknown
	C.bcm2835_i2c_setSlaveAddress(cAddr)
}

// Bcm2835_i2c_setClockDivider function as declared in bcm-go/bcm2835.h:1873
func Bcm2835_i2c_setClockDivider(Divider uint16) {
	cDivider, _ := (C.uint16_t)(Divider), cgoAllocsUnknown
	C.bcm2835_i2c_setClockDivider(cDivider)
}

// Bcm2835_i2c_set_baudrate function as declared in bcm-go/bcm2835.h:1881
func Bcm2835_i2c_set_baudrate(Baudrate uint32) {
	cBaudrate, _ := (C.uint32_t)(Baudrate), cgoAllocsUnknown
	C.bcm2835_i2c_set_baudrate(cBaudrate)
}

// Bcm2835_i2c_write function as declared in bcm-go/bcm2835.h:1889
func Bcm2835_i2c_write(Buf string, Len uint32) byte {
	Buf = safeString(Buf)
	cBuf, _ := unpackPCharString(Buf)
	cLen, _ := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.bcm2835_i2c_write(cBuf, cLen)
	runtime.KeepAlive(Buf)
	__v := (byte)(__ret)
	return __v
}

// Bcm2835_i2c_read function as declared in bcm-go/bcm2835.h:1897
func Bcm2835_i2c_read(Buf []byte, Len uint32) byte {
	cBuf, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Buf)).Data)), cgoAllocsUnknown
	cLen, _ := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.bcm2835_i2c_read(cBuf, cLen)
	__v := (byte)(__ret)
	return __v
}

// Bcm2835_i2c_read_register_rs function as declared in bcm-go/bcm2835.h:1913
func Bcm2835_i2c_read_register_rs(Regaddr *byte, Buf []byte, Len uint32) byte {
	cRegaddr, _ := (*C.char)(unsafe.Pointer(Regaddr)), cgoAllocsUnknown
	cBuf, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Buf)).Data)), cgoAllocsUnknown
	cLen, _ := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.bcm2835_i2c_read_register_rs(cRegaddr, cBuf, cLen)
	__v := (byte)(__ret)
	return __v
}

// Bcm2835_i2c_write_read_rs function as declared in bcm-go/bcm2835.h:1925
func Bcm2835_i2c_write_read_rs(Cmds []byte, Cmds_len uint32, Buf []byte, Buf_len uint32) byte {
	cCmds, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Cmds)).Data)), cgoAllocsUnknown
	cCmds_len, _ := (C.uint32_t)(Cmds_len), cgoAllocsUnknown
	cBuf, _ := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Buf)).Data)), cgoAllocsUnknown
	cBuf_len, _ := (C.uint32_t)(Buf_len), cgoAllocsUnknown
	__ret := C.bcm2835_i2c_write_read_rs(cCmds, cCmds_len, cBuf, cBuf_len)
	__v := (byte)(__ret)
	return __v
}

// Bcm2835_st_read function as declared in bcm-go/bcm2835.h:1937
func Bcm2835_st_read() uint64 {
	__ret := C.bcm2835_st_read()
	__v := (uint64)(__ret)
	return __v
}

// Bcm2835_st_delay function as declared in bcm-go/bcm2835.h:1943
func Bcm2835_st_delay(Offset_micros uint64, Micros uint64) {
	cOffset_micros, _ := (C.uint64_t)(Offset_micros), cgoAllocsUnknown
	cMicros, _ := (C.uint64_t)(Micros), cgoAllocsUnknown
	C.bcm2835_st_delay(cOffset_micros, cMicros)
}

// Bcm2835_pwm_set_clock function as declared in bcm-go/bcm2835.h:1960
func Bcm2835_pwm_set_clock(Divisor uint32) {
	cDivisor, _ := (C.uint32_t)(Divisor), cgoAllocsUnknown
	C.bcm2835_pwm_set_clock(cDivisor)
}

// Bcm2835_pwm_set_mode function as declared in bcm-go/bcm2835.h:1968
func Bcm2835_pwm_set_mode(Channel byte, Markspace byte, Enabled byte) {
	cChannel, _ := (C.uint8_t)(Channel), cgoAllocsUnknown
	cMarkspace, _ := (C.uint8_t)(Markspace), cgoAllocsUnknown
	cEnabled, _ := (C.uint8_t)(Enabled), cgoAllocsUnknown
	C.bcm2835_pwm_set_mode(cChannel, cMarkspace, cEnabled)
}

// Bcm2835_pwm_set_range function as declared in bcm-go/bcm2835.h:1975
func Bcm2835_pwm_set_range(Channel byte, _range uint32) {
	cChannel, _ := (C.uint8_t)(Channel), cgoAllocsUnknown
	c_range, _ := (C.uint32_t)(_range), cgoAllocsUnknown
	C.bcm2835_pwm_set_range(cChannel, c_range)
}

// Bcm2835_pwm_set_data function as declared in bcm-go/bcm2835.h:1983
func Bcm2835_pwm_set_data(Channel byte, Data uint32) {
	cChannel, _ := (C.uint8_t)(Channel), cgoAllocsUnknown
	cData, _ := (C.uint32_t)(Data), cgoAllocsUnknown
	C.bcm2835_pwm_set_data(cChannel, cData)
}
