// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 12 Aug 2020 14:17:19 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "bcm2835.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

