// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 12 Aug 2020 14:17:19 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
BCM2835 bindings
*/
package bcm2835go
