// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 12 Aug 2020 14:17:19 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package bcm2835go

/*
#cgo CFLAGS: -I. -DDEBUG -I${SRCDIR}/
#include "bcm2835.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
